name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@remove-repo-sync
    with:
      release_prefix: opera-rtc-s1-browse
      release_branch: main
      develop_branch: develop
      sync_pr_label: actions-bot
    secrets:
      USER_TOKEN: ${{ secrets.PAK }}
